services:
  network-monitor:
    build: .
    container_name: network-monitor
    volumes:
      - ./config_multi.yaml:/config/config.yaml:ro
      - ./logs:/app/logs
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
